"""
vlm/grpo/rollout.py  ·  AgenticRollout
========================================

Implements the agentic Markov Decision Process (MDP) rollout for GRPO training.

MDP formulation (DeepEyes arxiv 2505.14362, Eq. 1)
----------------------------------------------------
  State:   s_t = {question, image, Ultatron_tokens, X_{≤t}, I_{≤t}}
           where X_{≤t} = accumulated text tokens
                 I_{≤t} = accumulated SAM2 observation tokens
  Action:  a_t ~ π_θ(· | s_t)  (next token sampled from policy)
  Obs:     after <tool_call>…</tool_call>, SAM2 returns 2 obs tokens
           appended to s_t with loss_mask = 0

For each prompt we sample G independent trajectories in parallel (or serially
if memory-constrained) and return all trajectories for GRPO advantage computation.

Token-wise loss mask
--------------------
  loss_mask[t] = 1   token generated by the model (included in GRPO objective)
  loss_mask[t] = 0   SAM2 observation token or prompt token (excluded)
"""
from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

import torch

log = logging.getLogger(__name__)


@dataclass
class Trajectory:
    """A single generated trajectory with all metadata needed for GRPO."""
    token_ids:   List[int]    # all generated tokens (model + obs)
    loss_mask:   List[int]    # 1 = model, 0 = obs/prompt
    text:        str
    answer:      str
    tool_calls:  List[dict]
    reward:      Optional[float] = None
    reward_info: Dict[str, Any]  = field(default_factory=dict)


@dataclass
class RolloutBatch:
    """
    G trajectories for a single prompt, ready for GRPO advantage computation.

    Attributes
    ----------
    trajectories : list of G Trajectory objects
    prompt       : the text prompt used
    ground_truth : task ground-truth label
    task_type    : str
    dataset_id   : str
    """
    trajectories: List[Trajectory]
    prompt:       str
    ground_truth: Any
    task_type:    str
    dataset_id:   Optional[str]

    @property
    def rewards(self) -> List[float]:
        return [t.reward or 0.0 for t in self.trajectories]

    @property
    def n_tool_calls(self) -> List[int]:
        return [len(t.tool_calls) for t in self.trajectories]


class AgenticRollout:
    """
    Samples G trajectories per prompt via the StudentModel.generate_with_tools().

    Parameters
    ----------
    student        : StudentModel instance (contains LoRA Qwen + projector)
    reward_fn      : CompositeReward instance
    group_size     : G — number of rollouts per prompt (default 8)
    max_sam2_calls : maximum SAM2 tool invocations per trajectory (default 3)
    device         : inference device
    """

    def __init__(
        self,
        student:        Any,        # StudentModel
        reward_fn:      Any,        # CompositeReward
        group_size:     int  = 8,
        max_sam2_calls: int  = 3,
        device:         str  = "cuda",
    ):
        self.student        = student
        self.reward_fn      = reward_fn
        self.group_size     = group_size
        self.max_sam2_calls = max_sam2_calls
        self.device         = device

    # ── Main rollout ─────────────────────────────────────────────────────────

    @torch.no_grad()
    def rollout(
        self,
        sample: "VLMSample",        # noqa: F821 — from vlm.grpo.data
        ultatron_backbone: Optional[Any] = None,  # ImageBranch / VideoBranch from Ultatron
    ) -> RolloutBatch:
        """
        Generate G trajectories for a single VLMSample.

        Parameters
        ----------
        sample            : VLMSample from VLMDataModule
        ultatron_backbone : optional pre-loaded Ultatron branch to extract tokens on-the-fly
                            (if None, uses pre-extracted patch_tokens/tube_tokens from sample)

        Returns
        -------
        RolloutBatch with G trajectories and rewards assigned
        """
        patch_tokens, tube_tokens = self._extract_ultatron_tokens(sample, ultatron_backbone)

        trajectories: List[Trajectory] = []

        for g in range(self.group_size):
            try:
                gen_out = self.student.generate_with_tools(
                    prompt       = sample.prompt,
                    image        = sample.image,
                    patch_tokens = patch_tokens,
                    tube_tokens  = tube_tokens,
                )
                traj = Trajectory(
                    token_ids  = gen_out["token_ids"],
                    loss_mask  = gen_out["loss_mask"],
                    text       = gen_out["text"],
                    answer     = gen_out["answer"],
                    tool_calls = gen_out["tool_calls"],
                )
            except Exception as e:
                log.warning(f"Rollout g={g} failed: {e}")
                traj = Trajectory(
                    token_ids=[], loss_mask=[], text="", answer="", tool_calls=[]
                )
            trajectories.append(traj)

        # ── Assign rewards ────────────────────────────────────────────────────
        reward_dicts = self.reward_fn.compute_batch(
            trajectories = [{"text": t.text, "answer": t.answer, "tool_calls": t.tool_calls}
                             for t in trajectories],
            ground_truths = [sample.ground_truth] * self.group_size,
            task_types    = [sample.task_type]    * self.group_size,
            dataset_ids   = [sample.dataset_id]   * self.group_size,
            images        = [sample.image]        * self.group_size,
        )

        for traj, rdict in zip(trajectories, reward_dicts):
            traj.reward      = rdict["total"]
            traj.reward_info = rdict

        return RolloutBatch(
            trajectories = trajectories,
            prompt       = sample.prompt,
            ground_truth = sample.ground_truth,
            task_type    = sample.task_type,
            dataset_id   = sample.dataset_id,
        )

    # ── Batch rollout (multiple prompts) ─────────────────────────────────────

    @torch.no_grad()
    def rollout_batch(
        self,
        samples:           List["VLMSample"],  # noqa: F821
        ultatron_backbone: Optional[Any] = None,
    ) -> List[RolloutBatch]:
        """Rollout over a list of samples."""
        return [self.rollout(s, ultatron_backbone) for s in samples]

    # ── Token preparation for GRPO trainer ───────────────────────────────────

    def prepare_for_training(
        self,
        batch:     RolloutBatch,
        tokenizer: Any,
        device:    str = "cuda",
    ) -> Dict[str, Any]:
        """
        Convert a RolloutBatch into tensors ready for the GRPO trainer.

        Returns dict with:
          input_ids    : (G, L_max) padded token ID tensor
          loss_masks   : (G, L_max) 0/1 float tensor
          rewards      : (G,) float tensor
          advantages   : (G,) group-normalised advantages
          attention_mask : (G, L_max) attention mask
        """
        pad_id = tokenizer.pad_token_id or 0
        trajs  = batch.trajectories
        G      = len(trajs)

        # Pad to max length
        max_len = max((len(t.token_ids) for t in trajs), default=1)

        ids_list   = []
        masks_list = []
        for t in trajs:
            ids  = t.token_ids[:max_len]
            lm   = t.loss_mask[:max_len]
            # Right-pad
            pad_len = max_len - len(ids)
            ids_list.append(ids   + [pad_id] * pad_len)
            masks_list.append(lm  + [0]      * pad_len)

        input_ids    = torch.tensor(ids_list,   dtype=torch.long,  device=device)
        loss_masks   = torch.tensor(masks_list, dtype=torch.float, device=device)
        attention_mk = (input_ids != pad_id).long()

        rewards    = torch.tensor([t.reward or 0.0 for t in trajs],
                                   dtype=torch.float, device=device)
        # Group-normalised advantages
        advantages = _group_norm_advantages(rewards)

        return {
            "input_ids":      input_ids,
            "loss_masks":     loss_masks,
            "rewards":        rewards,
            "advantages":     advantages,
            "attention_mask": attention_mk,
        }

    # ── Ultatron token extraction ─────────────────────────────────────────────

    @torch.no_grad()
    def _extract_ultatron_tokens(
        self,
        sample:    "VLMSample",  # noqa: F821
        backbone:  Optional[Any],
    ) -> Tuple[Optional[torch.Tensor], Optional[torch.Tensor]]:
        """
        Extract patch / tube tokens from the Ultatron backbone.

        If the sample already has pre-extracted tensors, return them directly.
        Otherwise, run the frozen backbone forward.
        """
        # Pre-extracted (faster; produced by data loader)
        if getattr(sample, "patch_tokens", None) is not None:
            pt = sample.patch_tokens.to(self.device)
        elif backbone is not None and sample.image_tensor is not None:
            out = backbone.forward_teacher(
                sample.image_tensor.unsqueeze(0).to(self.device)
            )
            pt = out.get("patch_tokens")  # (1, N, D)
        else:
            pt = None

        if getattr(sample, "tube_tokens", None) is not None:
            tt = sample.tube_tokens.to(self.device)
        elif backbone is not None and sample.video_tensor is not None:
            out = backbone.vid_branch.teacher(
                sample.video_tensor.unsqueeze(0).to(self.device)
            )
            tt = out.get("tube_tokens")   # (1, T, D)
        else:
            tt = None

        return pt, tt


# ── Helper ───────────────────────────────────────────────────────────────────

def _group_norm_advantages(rewards: torch.Tensor, eps: float = 1e-6) -> torch.Tensor:
    """
    Group-relative normalisation of rewards → advantages.
    A_i = (R_i - mean(R)) / (std(R) + eps)
    """
    mean = rewards.mean()
    std  = rewards.std() + eps
    return (rewards - mean) / std
